import Header from "@/components/header";
import Head from "next/head";
import { useState } from "react";
import Footer from "@/components/Footer";
import { CloseModal } from "@/icons/social.js";
import Modal from "@/components/modal";

function Home() {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const handleModalClose = () => {
    setIsModalOpen(false);
  };
  return (
    <>
      <Head>
        <title>skillstream</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href={require("../icons/logo-color.png").default.src}
        />
      </Head>

      <main>
        <Header />
        <Modal />
        <Footer />
      </main>
    </>
  );
}

export default Home;
