import Header from "@/components/header";
import LeandingPage from "@/components/Footer";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>skillstream</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href={require("../icons/logo-color.png").default.src}
        />
      </Head>
      {/* here im using a svg  */}
      <main>
        <Header />
        <LeandingPage />
      </main>
    </>
  );
}
